stages:
  - build
  - publish

build:
  stage: build

  script:
    - echo "Restoring NuGet Packages..."
    - '"c:\nuget\nuget.exe" restore "Catarina.sln"'
    - ''
    - echo "Release build..."
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\msbuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "Catarina.sln" /p:DebugSymbols=false /p:DebugType=None /p:AllowedReferenceRelatedFileExtensions=none'
  tags: 
    - C#
    - Windows

publish:
  stage: publish

  script:
    - echo "Comperss..."
    - '"C:\GitLab-Runner\utils\comperss-zip.bat" Catarina'
  tags: 
    - C#
    - Windows
  dependencies:
    - build
