stages:
  - build
  - publish

build:
  stage: build

  script:
    - echo "Restoring NuGet Packages..."
    - '"c:\nuget\nuget.exe" restore "Catarina.sln"'
    - ''
    - echo "Release build..."
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\msbuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "Catarina.sln" /p:DebugSymbols=false /p:DebugType=None /p:AllowedReferenceRelatedFileExtensions=none'
  tags: 
    - C#
    - Windows

publish:
  stage: publish

  variables:
    GIT_STRATEGY: none


  script:
    - echo "Comperss..."
    - 'cmd /Q /C "D:\GitLab-Runner\scripts\packaging_zip.cmd" ./Catarina/bin/Release/* build_%CI_COMMIT_SHA:~0,8%.zip'
    - ''
    - echo "Publishing..."
    - 'cmd /Q /C "D:\GitLab-Runner\scripts\publish_ftp.cmd" ./build_%CI_COMMIT_SHA:~0,8%.zip Catarina/%CI_COMMIT_REF_NAME%/'
  tags: 
    - C#
    - Windows

  artifacts:
    paths:
    - build_%CI_COMMIT_SHA:~0,8%.zip
    expire_in: 1 week

  dependencies:
    - build
