stages:
  - build
  - publish

build:
  stage: build

  script:
    - echo "Restoring NuGet Packages..."
    - '"c:\nuget\nuget.exe" restore "Catarina.sln"'
    - ''
    - echo "Release build..."
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\msbuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "Catarina.sln" /p:DebugSymbols=false /p:DebugType=None /p:AllowedReferenceRelatedFileExtensions=none'
  tags: 
    - C#
    - Windows

publish:
  stage: publish

  variables:
    GIT_STRATEGY: none


  script:
    - echo "Comperss..."
    - '"D:\GitLab-Runner\scripts\packaging_zip.bat" ./Catarina/bin/Release/* build.zip'
    - echo "Publish to ftp server"
    - '"D:\GitLab-Runner\scripts\publish_ftp.bat" ./build.zip Catarina/%CI_COMMIT_REF_NAME%/'
  tags: 
    - C#
    - Windows

  artifacts:
    paths:
    - build.zip
    expire_in: 1 week

  dependencies:
    - build
